rootProject.name = "asnsei-the-right-waf"
include("talks:talk-10-kotlin-streams-good-bad:streams-gb-kafka")
include("talks:talk-10-kotlin-streams-good-bad:streams-gb-rabbitmq")
include("talks:talk-10-kotlin-streams-good-bad:streams-gb-single")
include("you-tube-sessions:long-videos:spot-on")
include("you-tube-sessions:long-videos:library-channels")
include("you-tube-sessions:long-videos:streams")
include("you-tube-sessions:long-videos:drinks-manager")
include("you-tube-sessions:long-videos:kotlin-keywords")
include("you-tube-sessions:long-videos:cooldrinks-juice-factory")
include("you-tube-sessions:overlay-shorts:jeorg-overlay-group-1")
include("you-tube-sessions:overlay-shorts:jeorg-overlays-group-1-spring")
include("you-tube-sessions:overlay-shorts:coroutines-demo")
include("experiments:coroutine-builders")
include("experiments:annotations-demo")