install-all:
	sudo apt-get install sbcl
	sudo apt-get install rlwrap
	sudo apt-get install cl-quicklisp
start-sbcl:
	sbcl --load /usr/share/common-lisp/source/quicklisp/quicklisp.lisp
start:
	rlwrap sbcl
