name: historic-tech Pull Request

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v5
        - name: Set up JDK 25
          uses: actions/setup-java@v5
          with:
            java-version: '25'
            distribution: 'adopt'

        - name: Build and Test
          run:  make b
